#!/bin/sh

echo "Guessing system type first!"

UNAME_MACHINE=`(uname -m) 2>/dev/null` || UNAME_MACHINE=unknown
UNAME_RELEASE=`(uname -r) 2>/dev/null` || UNAME_RELEASE=unknown
UNAME_SYSTEM=`(uname -s) 2>/dev/null` || UNAME_SYSTEM=unknown
UNAME_VERSION=`(uname -v) 2>/dev/null` || UNAME_VERSION=unknown

rm -f .architecture

case "${UNAME_MACHINE}:${UNAME_SYSTEM}:${UNAME_RELEASE}:${UNAME_VERSION}" in
    sun4*:SunOS:5.*:*)
        echo "ARCH=SUNOS5" > .architecture
        exit 0 ;;
    i86pc:SunOS:5.*:*)
        echo "ARCH=SUNOS5" > .architecture
        exit 0 ;;
    sun4*:SunOS:6*:*)
        echo "ARCH=SUNOS6" > .architecture
        exit 0 ;;
    sun4*:SunOS:*:*)
	echo "ARCH=SUNOS4" > .architecture
	exit 0 ;;
    *:Linux:*:*)
	echo "ARCH=LINUX" > .architecture
	exit 0
	;;
    *:Darwin:*:*)
	echo "ARCH=DARWIN" > .architecture
	exit 0
	;;
esac

echo '(Unable to guess system type)' 1>&2
exit 1